"""empty message

Revision ID: c1b887db75b5
Revises: 067a7037979e
Create Date: 2019-12-20 23:43:22.664699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b887db75b5'
down_revision = '067a7037979e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'post_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'post_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
